
const List<CountryCode> countries = [
  CountryCode(name: "Afghanistan", code: "AF", dialCode: "+93"),
  CountryCode(name: "Åland", code: "AX", dialCode: "+358"),
  CountryCode(name: "Shqipëria", code: "AL", dialCode: "+355"),
  CountryCode(name: "Algeria", code: "DZ", dialCode: "+213"),
  CountryCode(name: "American Samoa", code: "AS", dialCode: "+1684"),
  CountryCode(name: "Andorra", code: "AD", dialCode: "+376"),
  CountryCode(name: "Angola", code: "AO", dialCode: "+244"),
  CountryCode(name: "Anguilla", code: "AI", dialCode: "+1264"),
  CountryCode(name: "Antarctica", code: "AQ", dialCode: "+672"),
  CountryCode(name: "Antigua and Barbuda", code: "AG", dialCode: "+1268"),
  CountryCode(name: "Argentina", code: "AR", dialCode: "+54"),
  CountryCode(name: "Armenia", code: "AM", dialCode: "+374"),
  CountryCode(name: "Aruba", code: "AW", dialCode: "+297"),
  CountryCode(name: "Australia", code: "AU", dialCode: "+61"),
  CountryCode(name: "Austria", code: "AT", dialCode: "+43"),
  CountryCode(name: "Azərbaycan", code: "AZ", dialCode: "+994"),
  CountryCode(name: "Bahamas", code: "BS", dialCode: "+1242"),
  CountryCode(name: "Bahrain", code: "BH", dialCode: "+973"),
  CountryCode(name: "Bangladesh", code: "BD", dialCode: "+880"),
  CountryCode(name: "Barbados", code: "BB", dialCode: "+1246"),
  CountryCode(name: "Belarus", code: "BY", dialCode: "+375"),
  CountryCode(name: "Belgium", code: "BE", dialCode: "+32"),
  CountryCode(name: "Belize", code: "BZ", dialCode: "+501"),
  CountryCode(name: "Bénin", code: "BJ", dialCode: "+229"),
  CountryCode(name: "Bermuda", code: "BM", dialCode: "+1441"),
  CountryCode(name: "Bhutan", code: "BT", dialCode: "+975"),
  CountryCode(name: "Bolivia", code: "BO", dialCode: "+591"),
  CountryCode(name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387"),
  CountryCode(name: "Botswana", code: "BW", dialCode: "+267"),
  CountryCode(name: "Bouvetøya", code: "BV", dialCode: "+47"),
  CountryCode(name: "Brasil", code: "BR", dialCode: "+55"),
  CountryCode(
      name: "British Indian Ocean Territory", code: "IO", dialCode: "+246"),
  CountryCode(name: "Negara Brunei Darussalam", code: "BN", dialCode: "+673"),
  CountryCode(name: "Bulgaria", code: "BG", dialCode: "+359"),
  CountryCode(name: "Burkina Faso", code: "BF", dialCode: "+226"),
  CountryCode(name: "Burundi", code: "BI", dialCode: "+257"),
  CountryCode(name: "Cambodia", code: "KH", dialCode: "+855"),
  CountryCode(name: "Cameroon", code: "CM", dialCode: "+237"),
  CountryCode(name: "Canada", code: "CA", dialCode: "+1"),
  CountryCode(name: "Cabo Verde", code: "CV", dialCode: "+238"),
  CountryCode(name: "Cayman Islands", code: "KY", dialCode: "+1345"),
  CountryCode(name: "Central African Republic ", code: "CF", dialCode: "+236"),
  CountryCode(name: "Chad", code: "TD", dialCode: "+235"),
  CountryCode(name: "Chile", code: "CL", dialCode: "+56"),
  CountryCode(name: "China", code: "CN", dialCode: "+86"),
  CountryCode(name: "Christmas Island", code: "CX", dialCode: "+61"),
  CountryCode(name: "Cocos (Keeling) Islands", code: "CC", dialCode: "+61"),
  CountryCode(name: "Colombia", code: "CO", dialCode: "+57"),
  CountryCode(name: "Komori", code: "KM", dialCode: "+269"),
  CountryCode(name: "Congo", code: "CG", dialCode: "+242"),
  CountryCode(
      name: "Congo (Democratic Republic)", code: "CD", dialCode: "+243"),
  CountryCode(name: "Cook Islands", code: "CK", dialCode: "+682"),
  CountryCode(name: "Costa Rica", code: "CR", dialCode: "+506"),
  CountryCode(name: "Côte d'Ivoire", code: "CI", dialCode: "+225"),
  CountryCode(name: "Croatia", code: "HR", dialCode: "+385"),
  CountryCode(name: "Cuba", code: "CU", dialCode: "+53"),
  CountryCode(name: "Cyprus", code: "CY", dialCode: "+357"),
  CountryCode(name: "Czechia", code: "CZ", dialCode: "+420"),
  CountryCode(name: "Denmark", code: "DK", dialCode: "+45"),
  CountryCode(name: "Djibouti", code: "DJ", dialCode: "+253"),
  CountryCode(name: "Dominica", code: "DM", dialCode: "+1767"),
  CountryCode(name: "Dominican Republic", code: "DO", dialCode: "+1"),
  CountryCode(name: "Ecuador", code: "EC", dialCode: "+593"),
  CountryCode(name: "Egypt", code: "EG", dialCode: "+20"),
  CountryCode(name: "El Salvador", code: "SV", dialCode: "+503"),
  CountryCode(name: "Equatorial Guinea", code: "GQ", dialCode: "+240"),
  CountryCode(name: "Eritrea", code: "ER", dialCode: "+291"),
  CountryCode(name: "Estonia", code: "EE", dialCode: "+372"),
  CountryCode(name: "Ethiopia", code: "ET", dialCode: "+251"),
  CountryCode(
      name: "Falkland Islands (Malvinas]", code: "FK", dialCode: "+500"),
  CountryCode(name: "Faroe Islands", code: "FO", dialCode: "+298"),
  CountryCode(name: "Fiji", code: "FJ", dialCode: "+679"),
  CountryCode(name: "Finland", code: "FI", dialCode: "+358"),
  CountryCode(name: "France", code: "FR", dialCode: "+33"),
  CountryCode(name: "French Guiana", code: "GF", dialCode: "+594"),
  CountryCode(name: "French Polynesia", code: "PF", dialCode: "+689"),
  CountryCode(
      name: "French Southern Territories", code: "TF", dialCode: "+262"),
  CountryCode(name: "Gabon", code: "GA", dialCode: "+241"),
  CountryCode(name: "Gambia", code: "GM", dialCode: "+220"),
  CountryCode(name: "Georgia", code: "GE", dialCode: "+995"),
  CountryCode(name: "Germany", code: "DE", dialCode: "+49"),
  CountryCode(name: "Ghana", code: "GH", dialCode: "+233"),
  CountryCode(name: "Gibraltar", code: "GI", dialCode: "+350"),
  CountryCode(name: "Greece", code: "GR", dialCode: "+30"),
  CountryCode(name: "Greenland", code: "GL", dialCode: "+299"),
  CountryCode(name: "Grenada", code: "GD", dialCode: "+1473"),
  CountryCode(name: "Guadeloupe", code: "GP", dialCode: "+590"),
  CountryCode(name: "Guam", code: "GU", dialCode: "+1671"),
  CountryCode(name: "Guatemala", code: "GT", dialCode: "+502"),
  CountryCode(name: "Guernsey", code: "GG", dialCode: "+44"),
  CountryCode(name: "Guinea", code: "GN", dialCode: "+224"),
  CountryCode(name: "Guinea-Bissau", code: "GW", dialCode: "+245"),
  CountryCode(name: "Guyana", code: "GY", dialCode: "+592"),
  CountryCode(name: "Haiti", code: "HT", dialCode: "+509"),
  CountryCode(
      name: "Heard Island and McDonald Islands", code: "HM", dialCode: "+0"),
  CountryCode(name: "Vatican", code: "VA", dialCode: "+379"),
  CountryCode(name: "Honduras", code: "HN", dialCode: "+504"),
  CountryCode(name: "Hong Kong", code: "HK", dialCode: "+852"),
  CountryCode(name: "Hungary", code: "HU", dialCode: "+36"),
  CountryCode(name: "Iceland", code: "IS", dialCode: "+354"),
  CountryCode(name: "India", code: "IN", dialCode: "+91"),
  CountryCode(name: "Indonesia", code: "ID", dialCode: "+62"),
  CountryCode(name: "Iran", code: "IR", dialCode: "+98"),
  CountryCode(name: "Iraq", code: "IQ", dialCode: "+964"),
  CountryCode(name: "Ireland", code: "IE", dialCode: "+353"),
  CountryCode(name: "Isle of Man", code: "IM", dialCode: "+44"),
  CountryCode(name: "Israel", code: "IL", dialCode: "+972"),
  CountryCode(name: "Italy", code: "IT", dialCode: "+39"),
  CountryCode(name: "Jamaica", code: "JM", dialCode: "+1876"),
  CountryCode(name: "Japan", code: "JP", dialCode: "+81"),
  CountryCode(name: "Jersey", code: "JE", dialCode: "+44"),
  CountryCode(name: "Jordan", code: "JO", dialCode: "+962"),
  CountryCode(name: "Kazakhstan", code: "KZ", dialCode: "+7"),
  CountryCode(name: "Kenya", code: "KE", dialCode: "+254"),
  CountryCode(name: "Kiribati", code: "KI", dialCode: "+686"),
  CountryCode(
      name: "Korea Democratic People's Republic", code: "KP", dialCode: "+850"),
  CountryCode(name: "Korea", code: "KR", dialCode: "+82"),
  CountryCode(name: "Kosovo", code: "XK", dialCode: "+383"),
  CountryCode(name: "Kuwait", code: "KW", dialCode: "+965"),
  CountryCode(name: "Kyrgyzstan", code: "KG", dialCode: "+996"),
  CountryCode(
      name: "Lao People's Democratic Republic", code: "LA", dialCode: "+856"),
  CountryCode(name: "Latvia", code: "LV", dialCode: "+371"),
  CountryCode(name: "Lebanon", code: "LB", dialCode: "+961"),
  CountryCode(name: "Lesotho", code: "LS", dialCode: "+266"),
  CountryCode(name: "Liberia", code: "LR", dialCode: "+231"),
  CountryCode(name: "Libya", code: "LY", dialCode: "+218"),
  CountryCode(name: "Liechtenstein", code: "LI", dialCode: "+423"),
  CountryCode(name: "Lithuania", code: "LT", dialCode: "+370"),
  CountryCode(name: "Luxembourg", code: "LU", dialCode: "+352"),
  CountryCode(name: "Macao", code: "MO", dialCode: "+853"),
  CountryCode(
      name: " Macedonia (North Republic)", code: "MK", dialCode: "+389"),
  CountryCode(name: "Madagascar", code: "MG", dialCode: "+261"),
  CountryCode(name: "Malawi", code: "MW", dialCode: "+265"),
  CountryCode(name: "Malaysia", code: "MY", dialCode: "+60"),
  CountryCode(name: "Maldives", code: "MV", dialCode: "+960"),
  CountryCode(name: "Mali", code: "ML", dialCode: "+223"),
  CountryCode(name: "Malta", code: "MT", dialCode: "+356"),
  CountryCode(name: "Marshall Islands", code: "MH", dialCode: "+692"),
  CountryCode(name: "Martinique", code: "MQ", dialCode: "+596"),
  CountryCode(name: "Mauritania", code: "MR", dialCode: "+222"),
  CountryCode(name: "Mauritius", code: "MU", dialCode: "+230"),
  CountryCode(name: "Mayotte", code: "YT", dialCode: "+262"),
  CountryCode(name: "México", code: "MX", dialCode: "+52"),
  CountryCode(name: "Micronesia", code: "FM", dialCode: "+691"),
  CountryCode(name: "Moldova", code: "MD", dialCode: "+373"),
  CountryCode(name: "Monaco", code: "MC", dialCode: "+377"),
  CountryCode(name: "Mongolia", code: "MN", dialCode: "+976"),
  CountryCode(name: "Montenegro", code: "ME", dialCode: "+382"),
  CountryCode(name: "Montserrat", code: "MS", dialCode: "+1664"),
  CountryCode(name: "Morocco", code: "MA", dialCode: "+212"),
  CountryCode(name: "Mozambique", code: "MZ", dialCode: "+258"),
  CountryCode(name: "Myanmar", code: "MM", dialCode: "+95"),
  CountryCode(name: "Namibia", code: "NA", dialCode: "+264"),
  CountryCode(name: "Nauru", code: "NR", dialCode: "+674"),
  CountryCode(name: "Nepal", code: "NP", dialCode: "+977"),
  CountryCode(name: "Netherlands", code: "NL", dialCode: "+31"),
  CountryCode(name: "Netherlands Antilles", code: "AN", dialCode: "+599"),
  CountryCode(name: "New Caledonia", code: "NC", dialCode: "+687"),
  CountryCode(name: "New Zealand", code: "NZ", dialCode: "+64"),
  CountryCode(name: "Nicaragua", code: "NI", dialCode: "+505"),
  CountryCode(name: "Niger", code: "NE", dialCode: "+227"),
  CountryCode(name: "Nigeria", code: "NG", dialCode: "+234"),
  CountryCode(name: "Niue", code: "NU", dialCode: "+683"),
  CountryCode(name: "Norfolk Island", code: "NF", dialCode: "+672"),
  CountryCode(name: "Northern Mariana Islands", code: "MP", dialCode: "+1670"),
  CountryCode(name: "Norway", code: "NO", dialCode: "+47"),
  CountryCode(name: "Oman", code: "OM", dialCode: "+968"),
  CountryCode(name: "Pakistan", code: "PK", dialCode: "+92"),
  CountryCode(name: "Palau", code: "PW", dialCode: "+680"),
  CountryCode(name: "Palestine", code: "PS", dialCode: "+970"),
  CountryCode(name: "Panamá", code: "PA", dialCode: "+507"),
  CountryCode(name: "Papua Niugini", code: "PG", dialCode: "+675"),
  CountryCode(name: "Paraguay", code: "PY", dialCode: "+595"),
  CountryCode(name: "Perú", code: "PE", dialCode: "+51"),
  CountryCode(name: "Philippines", code: "PH", dialCode: "+63"),
  CountryCode(name: "Pitcairn Islands", code: "PN", dialCode: "+64"),
  CountryCode(name: "Poland", code: "PL", dialCode: "+48"),
  CountryCode(name: "Portugal", code: "PT", dialCode: "+351"),
  CountryCode(name: "Puerto Rico", code: "PR", dialCode: "+1939"),
  CountryCode(name: "Puerto Rico", code: "PR", dialCode: "+1787"),
  CountryCode(name: "Qatar", code: "QA", dialCode: "+974"),
  CountryCode(name: "Romania", code: "RO", dialCode: "+40"),
  CountryCode(name: "Russian Federation", code: "RU", dialCode: "+7"),
  CountryCode(name: "Rwanda", code: "RW", dialCode: "+250"),
  CountryCode(name: "La Réunion", code: "RE", dialCode: "+262"),
  CountryCode(name: "Saint-Barthélemy", code: "BL", dialCode: "+590"),
  CountryCode(name: "Saint Helena", code: "SH", dialCode: "+290"),
  CountryCode(name: "Saint Kitts and Nevis", code: "KN", dialCode: "+1869"),
  CountryCode(name: "Saint Lucia", code: "LC", dialCode: "+1758"),
  CountryCode(name: "Saint-Martin", code: "MF", dialCode: "+590"),
  CountryCode(name: "Saint Pierre and Miquelon", code: "PM", dialCode: "+508"),
  CountryCode(
      name: "Saint Vincent and the Grenadines", code: "VC", dialCode: "+1784"),
  CountryCode(name: "Samoa", code: "WS", dialCode: "+685"),
  CountryCode(name: "San Marino", code: "SM", dialCode: "+378"),
  CountryCode(name: "Sao Tome and Principe", code: "ST", dialCode: "+239"),
  CountryCode(name: "Saudi Arabia", code: "SA", dialCode: "+966"),
  CountryCode(name: "Senegal", code: "SN", dialCode: "+221"),
  CountryCode(name: "Serbia", code: "RS", dialCode: "+381"),
  CountryCode(name: "Seychelles", code: "SC", dialCode: "+248"),
  CountryCode(name: "Sierra Leone", code: "SL", dialCode: "+232"),
  CountryCode(name: "Singapore", code: "SG", dialCode: "+65"),
  CountryCode(name: "Slovakia", code: "SK", dialCode: "+421"),
  CountryCode(name: "Slovenia", code: "SI", dialCode: "+386"),
  CountryCode(name: "Solomon Islands", code: "SB", dialCode: "+677"),
  CountryCode(name: "Somalia", code: "SO", dialCode: "+252"),
  CountryCode(name: "South Africa", code: "ZA", dialCode: "+27"),
  CountryCode(name: "South Sudan", code: "SS", dialCode: "+211"),
  CountryCode(name: "South Georgia", code: "GS", dialCode: "+500"),
  CountryCode(name: "Spain", code: "ES", dialCode: "+34"),
  CountryCode(name: "Sri Lanka", code: "LK", dialCode: "+94"),
  CountryCode(name: "Sudan", code: "SD", dialCode: "+249"),
  CountryCode(name: "Suriname", code: "SR", dialCode: "+597"),
  CountryCode(name: "Svalbard and Jan Mayen", code: "SJ", dialCode: "+47"),
  CountryCode(name: "Eswatini", code: "SZ", dialCode: "+268"),
  CountryCode(name: "Sweden", code: "SE", dialCode: "+46"),
  CountryCode(name: "Switzerland", code: "CH", dialCode: "+41"),
  CountryCode(name: "Syrian Arab Republic", code: "SY", dialCode: "+963"),
  CountryCode(name: "Taiwan", code: "TW", dialCode: "+886"),
  CountryCode(name: "Tajikistan", code: "TJ", dialCode: "+992"),
  CountryCode(name: "Tanzania", code: "TZ", dialCode: "+255"),
  CountryCode(name: "Thailand", code: "TH", dialCode: "+66"),
  CountryCode(name: "Timor-Leste", code: "TL", dialCode: "+670"),
  CountryCode(name: "Togo", code: "TG", dialCode: "+228"),
  CountryCode(name: "Tokelau", code: "TK", dialCode: "+690"),
  CountryCode(name: "Tonga", code: "TO", dialCode: "+676"),
  CountryCode(name: "Trinidad and Tobago", code: "TT", dialCode: "+1868"),
  CountryCode(name: "Tunisia", code: "TN", dialCode: "+216"),
  CountryCode(name: "Turkey", code: "TR", dialCode: "+90"),
  CountryCode(name: "Turkmenistan", code: "TM", dialCode: "+993"),
  CountryCode(name: "Turks and Caicos Islands", code: "TC", dialCode: "+1649"),
  CountryCode(name: "Tuvalu", code: "TV", dialCode: "+688"),
  CountryCode(name: "Uganda", code: "UG", dialCode: "+256"),
  CountryCode(name: "Ukraine", code: "UA", dialCode: "+380"),
  CountryCode(name: "United Arab Emirates", code: "AE", dialCode: "+971"),
  CountryCode(name: "United Kingdom", code: "GB", dialCode: "+44"),
  CountryCode(name: "United States", code: "US", dialCode: "+1"),
  CountryCode(name: "Uruguay", code: "UY", dialCode: "+598"),
  CountryCode(name: "Uzbekistan", code: "UZ", dialCode: "+998"),
  CountryCode(name: "Vanuatu", code: "VU", dialCode: "+678"),
  CountryCode(name: "Venezuela", code: "VE", dialCode: "+58"),
  CountryCode(name: "Viet Nam", code: "VN", dialCode: "+84"),
  CountryCode(name: "British Virgin Islands", code: "VG", dialCode: "+1284"),
  CountryCode(
      name: "United States Virgin Islands", code: "VI", dialCode: "+1340"),
  CountryCode(name: "Wallis and Futuna", code: "WF", dialCode: "+681"),
  CountryCode(name: "Yemen", code: "YE", dialCode: "+967"),
  CountryCode(name: "Zambia", code: "ZM", dialCode: "+260"),
  CountryCode(name: "Zimbabwe", code: "ZW", dialCode: "+263"),
];

class CountryCode {
  const CountryCode({
    required this.name,
    required this.code,
    required this.dialCode,
  });

  final String name;
  final String code;
  final String dialCode;

  @override
  bool operator ==(covariant CountryCode other) {
    if (identical(this, other)) return true;

    return other.name == name &&
        other.code == code &&
        other.dialCode == dialCode;
  }

  @override
  int get hashCode => name.hashCode ^ code.hashCode ^ dialCode.hashCode;

  static CountryCode? fromCode(String? code) {
    if (code == null) return null;

    final index =
        countries.indexWhere((c) => c.code.toUpperCase() == code.toUpperCase());
    if (index == -1) return null;

    return countries[index];
  }
}

CountryCode? getCountryFromPhone(String phone) {
  for (final country in countries) {
    if (phone.startsWith(country.dialCode)) {
      return country;
    }
  }
  return null; // fallback if no match
}

String? getCountryCodeByName(String countryName) {
  try {
    return countries.firstWhere((country) => country.name == countryName).code;
  } catch (e) {
    return null;
  }
}

extension CountryNameExtension on String {
  String get countryCode {
    final name = trim().toLowerCase();

    const map = {
      'afghanistan': 'AF',
      'albania': 'AL',
      'algeria': 'DZ',
      'andorra': 'AD',
      'angola': 'AO',
      'argentina': 'AR',
      'armenia': 'AM',
      'australia': 'AU',
      'austria': 'AT',
      'azerbaijan': 'AZ',
      'bahamas': 'BS',
      'bahrain': 'BH',
      'bangladesh': 'BD',
      'barbados': 'BB',
      'belarus': 'BY',
      'belgium': 'BE',
      'belize': 'BZ',
      'benin': 'BJ',
      'bhutan': 'BT',
      'bolivia': 'BO',
      'bosnia and herzegovina': 'BA',
      'botswana': 'BW',
      'brazil': 'BR',
      'brunei': 'BN',
      'bulgaria': 'BG',
      'burkina faso': 'BF',
      'burundi': 'BI',
      'cambodia': 'KH',
      'cameroon': 'CM',
      'canada': 'CA',
      'cape verde': 'CV',
      'central african republic': 'CF',
      'chad': 'TD',
      'chile': 'CL',
      'china': 'CN',
      'colombia': 'CO',
      'comoros': 'KM',
      'congo': 'CG',
      'costa rica': 'CR',
      'croatia': 'HR',
      'cuba': 'CU',
      'cyprus': 'CY',
      'czech republic': 'CZ',
      'denmark': 'DK',
      'djibouti': 'DJ',
      'dominica': 'DM',
      'dominican republic': 'DO',
      'ecuador': 'EC',
      'egypt': 'EG',
      'el salvador': 'SV',
      'equatorial guinea': 'GQ',
      'eritrea': 'ER',
      'estonia': 'EE',
      'eswatini': 'SZ',
      'ethiopia': 'ET',
      'fiji': 'FJ',
      'finland': 'FI',
      'france': 'FR',
      'gabon': 'GA',
      'gambia': 'GM',
      'georgia': 'GE',
      'germany': 'DE',
      'ghana': 'GH',
      'greece': 'GR',
      'grenada': 'GD',
      'guatemala': 'GT',
      'guinea': 'GN',
      'guinea-bissau': 'GW',
      'guyana': 'GY',
      'haiti': 'HT',
      'honduras': 'HN',
      'hungary': 'HU',
      'iceland': 'IS',
      'india': 'IN',
      'indonesia': 'ID',
      'iran': 'IR',
      'iraq': 'IQ',
      'ireland': 'IE',
      'israel': 'IL',
      'italy': 'IT',
      'jamaica': 'JM',
      'japan': 'JP',
      'jordan': 'JO',
      'kazakhstan': 'KZ',
      'kenya': 'KE',
      'kiribati': 'KI',
      'kuwait': 'KW',
      'kyrgyzstan': 'KG',
      'laos': 'LA',
      'latvia': 'LV',
      'lebanon': 'LB',
      'lesotho': 'LS',
      'liberia': 'LR',
      'libya': 'LY',
      'liechtenstein': 'LI',
      'lithuania': 'LT',
      'luxembourg': 'LU',
      'madagascar': 'MG',
      'malawi': 'MW',
      'malaysia': 'MY',
      'maldives': 'MV',
      'mali': 'ML',
      'malta': 'MT',
      'marshall islands': 'MH',
      'mauritania': 'MR',
      'mauritius': 'MU',
      'mexico': 'MX',
      'micronesia': 'FM',
      'moldova': 'MD',
      'monaco': 'MC',
      'mongolia': 'MN',
      'montenegro': 'ME',
      'morocco': 'MA',
      'mozambique': 'MZ',
      'myanmar': 'MM',
      'namibia': 'NA',
      'nepal': 'NP',
      'netherlands': 'NL',
      'new zealand': 'NZ',
      'nicaragua': 'NI',
      'niger': 'NE',
      'nigeria': 'NG',
      'north korea': 'KP',
      'north macedonia': 'MK',
      'norway': 'NO',
      'oman': 'OM',
      'pakistan': 'PK',
      'palau': 'PW',
      'panama': 'PA',
      'papua new guinea': 'PG',
      'paraguay': 'PY',
      'peru': 'PE',
      'philippines': 'PH',
      'poland': 'PL',
      'portugal': 'PT',
      'qatar': 'QA',
      'romania': 'RO',
      'russia': 'RU',
      'rwanda': 'RW',
      'saint kitts and nevis': 'KN',
      'saint lucia': 'LC',
      'saint vincent and the grenadines': 'VC',
      'samoa': 'WS',
      'san marino': 'SM',
      'sao tome and principe': 'ST',
      'saudi arabia': 'SA',
      'senegal': 'SN',
      'serbia': 'RS',
      'seychelles': 'SC',
      'sierra leone': 'SL',
      'singapore': 'SG',
      'slovakia': 'SK',
      'slovenia': 'SI',
      'solomon islands': 'SB',
      'somalia': 'SO',
      'south africa': 'ZA',
      'south korea': 'KR',
      'south sudan': 'SS',
      'spain': 'ES',
      'sri lanka': 'LK',
      'sudan': 'SD',
      'suriname': 'SR',
      'sweden': 'SE',
      'switzerland': 'CH',
      'syria': 'SY',
      'taiwan': 'TW',
      'tajikistan': 'TJ',
      'tanzania': 'TZ',
      'thailand': 'TH',
      'timor-leste': 'TL',
      'togo': 'TG',
      'tonga': 'TO',
      'trinidad and tobago': 'TT',
      'tunisia': 'TN',
      'turkey': 'TR',
      'turkmenistan': 'TM',
      'tuvalu': 'TV',
      'uganda': 'UG',
      'ukraine': 'UA',
      'united arab emirates': 'AE',
      'united kingdom': 'GB',
      'united states': 'US',
      'uruguay': 'UY',
      'uzbekistan': 'UZ',
      'vanuatu': 'VU',
      'venezuela': 'VE',
      'vietnam': 'VN',
      'yemen': 'YE',
      'zambia': 'ZM',
      'zimbabwe': 'ZW',
    };

    return map[name] ?? "PK";
  }
}
