// ignore_for_file: type_annotate_public_apis

import 'package:firebase_auth/firebase_auth.dart';
import 'package:wave_drive/core/services/firebase/consts.dart';
import 'package:wave_drive/core/shared/utils/app_logger.dart';


@Deprecated("Deprecated")
class PhoneAuthService {
  int? _resendToken;
  final _firebaseAuth = FirebaseAuth.instance;

  @Deprecated("Deprecated")
  Future<void> verifyPhoneNumber({
    required String phoneNumber,
    required Function(String? verificationId) codeSent,
    required Function(PhoneAuthCredential) verificationCompleted,
    required Function(FirebaseAuthException) verificationFailed,
    required Function(String?) codeAutoRetrievalTimeout,
  }) async {
    try {
      await _firebaseAuth.verifyPhoneNumber(
        phoneNumber: "$phoneNumber",
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: (String verificationId, int? resendToken) {
          AppLogger.d('Code sent id: $verificationId');
          _resendToken = resendToken;
          codeSent(verificationId);
        },
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
        forceResendingToken: _resendToken,
      );
    } catch (error) {
      AppLogger.e('Sign in with phone number error', error: error);
      rethrow;
    }
  }

  @Deprecated("Deprecated")
  Future<SocialLoginResponse> signInWithCredential(
    credential, {
    required String verificationId,
    required String otp,
  }) async {
    try {
      final credential = PhoneAuthProvider.credential(
        verificationId: verificationId,
        smsCode: otp,
      );
      final userCredential = await _firebaseAuth.signInWithCredential(
        credential,
      );

      return SocialLoginResponse(
        status: SocialLoginStatus.success,
        userCredential: userCredential,
      );
    } catch (e) {
      AppLogger.e("Sign in error $e");
      if (e is FirebaseAuthException) {
        return SocialLoginResponse(
          status: SocialLoginStatus.failed,
          errorCode: e.code,
        );
      }
      return SocialLoginResponse(status: SocialLoginStatus.failed);
    }
  }

  @Deprecated("Deprecated")
  Future<SocialLoginResponse> signInWithAutoGeneratedCredential({
    required PhoneAuthCredential credential,
  }) async {
    try {
      final userCredential = await _firebaseAuth.signInWithCredential(
        credential,
      );
      return SocialLoginResponse(
        status: SocialLoginStatus.success,
        userCredential: userCredential,
      );
    } catch (e) {
      AppLogger.e("Sign in error $e");
      if (e is FirebaseAuthException) {
        return SocialLoginResponse(
          status: SocialLoginStatus.failed,
          errorCode: e.code,
        );
      }
      return SocialLoginResponse(status: SocialLoginStatus.failed);
    }
  }
}
