// part of 'auth_cubit.dart';

// @freezed
// abstract class AuthState with _$AuthState {
//   const factory AuthState({
//     // required OTPState otpState,
//     @Default(false) bool isLoggedIn,
//     @Default(AppLoadState.initial) AppLoadState signInState,
//     @Default(AppLoadState.initial) AppLoadState signInSocialState,
//     @Default(AppLoadState.initial) AppLoadState completeProfileState,
//     @Default(AppLoadState.initial) AppLoadState completeCreatePassword,
//     int? statusCodeSignInWithPassword,
//     @Default("") String errorMessage,
//   }) = _AuthState;
// }

// // @freezed
// // class OTPState with _$OTPState {
// //   const factory OTPState({
// //     @Default(AppLoadState.initial) AppLoadState verifyStatus,
// //     @Default(AppLoadState.initial) AppLoadState resendStatus,
// //     @Default(AppLoadState.initial) AppLoadState confirmStatus,
// //     String? confirmErrorText,
// //     String? verifyErrorText,
// //     String? verificationId,
// //     String? smsCode,
// //     String? phoneNumber,
// //     String? countryCode,
// //     PhoneAuthCredential? autoGeneratedCredential,
// //   }) = _OTPState;
// // }
